#!/bin/bash -xe
module=$1
architecture=$2
result_directory=$3

if [ "$architecture" == "i386" ]; then
    kernel_architecture="686"
else
    kernel_architecture=$architecture
fi

export KPKG_DEST_DIR=$result_directory
apt-get update 
apt-get -y --force-yes install module-assistant $module-source 

function linux_headers_packages() {
    linux_headers_packages=`apt-cache search linux-headers-2.6 | awk '{ print $1 }' | egrep "linux-headers-2\.6\.[0-9]{2}-[0-9]+-($kernel_architecture|generic|rt)\$"`
#     if [ -z "$linux_headers_packages" ]; then
#         # ubuntu linux headers aren't prefixed by 686 or amd64
#         linux_headers_packages=`apt-cache search linux-headers-2.6 | awk '{ print $1 }' | egrep "linux-headers-2\.6\.[0-9]{2}-[0-9]+$"`
#     fi
    echo $linux_headers_packages
}

apt-get -y --force-yes install `linux_headers_packages`

kernel_versions=`linux_headers_packages | sed 's/linux-headers-//g' | sed "s/ /,/g"`

set +e

module-assistant --non-inter --kvers-list $kernel_versions prepare,get,build $module

ma_error_code=$?
[ $ma_error_code == 249 ] && exit 0
exit $ma_error_code
