#!/bin/bash -e
module=$1
architecture=$2
result_directory=$3

if [ "$architecture" == "i386" ]; then
    kernel_architecture="686"
else
    kernel_architecture=$architecture
fi

export KPKG_DEST_DIR=$result_directory

apt-get update 
apt-get -y --force-yes install module-assistant 

function linux_headers_packages() {
    apt-cache search linux-headers-2.6 | awk '{ print $1 }' | egrep "linux-headers-2\.6\.[0-9]{2}-[0-9]+-($kernel_architecture|generic|rt)\$"
}

# module-assistant can make it, but --force-yes is sometimes usefull
apt-get -y --force-yes install `linux_headers_packages`

kernel_versions=`linux_headers_packages | sed 's/linux-headers-//g' | paste --serial --delimiter=,`

set +e
module-assistant --non-inter --kvers-list $kernel_versions prepare,get,build $module

ma_error_code=$?
# module-assistant --non-inter exists normally with 249 error code ...
[ $ma_error_code == 249 ] && exit 0

exit $ma_error_code
