# Common functions for debconf scripts

DEBCONF_PACKAGE=${DEBCONF_PACKAGE:-rivendell}
. /usr/share/debconf/confmodule

# Is the user configuring with debconf?
db_get rivendell/debconfenable
if [ "$RET" != "true" ]; then
    exit 0
fi

function db_print() {
    db_get "rivendell/$1"
    echo $RET
}

function backup_file() {
    file=$1
    if [ -e "$file" ]; then
        cp -a "$file" "${file}.dpkg-save"
    fi
}

function write_warning_header() {
    cat > $1 <<EOF
; NOTE: this file was generated by the rivendell debian package
;
; DO NOT EDIT THIS FILE!  Your changes will be lost on the next upgrade.
;
; To regenerate this file (or to select manual configuration) run the command:
;     dpkg-reconfigure rivendell
;
; Generated on `date "+%F %T"`
EOF
}

function write_input_into() {
    file=$1

    backup_file $file
    write_warning_header $file

    cat >> $file
}

